apiVersion: v1
kind: Service
metadata:
  name: lol-replay-server-v1
  labels:
    api: v1
    app: lol-replay-server
    env: prod
spec:
  selector:
    api: v1
    app: lol-replay-server
    env: prod
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30303
  type: LoadBalancer
