apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lol-replay-server-v1
spec:
  replicas: 1
  minReadySeconds: 30
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        api: v1
        app: lol-replay-server
        env: staging
    spec:
      containers:
      - env:
        - name: PORT
          value: :8080
        - name: GOOG_CREDS_JSON
          value: /etc/creds/gcp-staging1
        - name: GOOG_PROJECT_ID
          value: vs-staging1
        - name: GCS_REPLAY_PREFIX
          value: gs://vss-esports/lol/replay/matches
        image: gcr.io/vs-containers/lol-replay-server
        imagePullPolicy: Always
        name: lol-replay-server-v1
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: 20m
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /etc/creds
          name: creds-staging
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: creds-staging
        secret:
          secretName: creds-staging
