apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lol-eloprocess-runner-v1
spec:
  replicas: 1
  minReadySeconds: 30
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: lol-eloprocess-runner
        env: staging
        api: v1
    spec:
      containers:
      - env:
        - name: GOOG_CREDS_JSON
          value: /etc/creds/gcp-staging1
        - name: GOOG_PROJECT_ID
          value: vs-staging1
        - name: OUTPUT_DIR
          value: gs://vss-esports/lol/baseview
        - name: PUBSUB_INPUT_SUB
          value: lol_eloprocess
        - name: PUBSUB_OUTPUT_TOPIC
          value: lol_advanced_stats_ingest
        - name: REPLAY_DATA_DIR
          value: gs://vss-esports/lol/replay/matches
        image: gcr.io/vs-containers/lol-eloprocess-runner:new
        imagePullPolicy: Always
        name: lol-eloprocess-runner-v1
        resources:
          requests:
            cpu: 10m
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /etc/creds
          name: creds-staging
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: creds-staging
        secret:
          secretName: creds-staging
