apiVersion: v1
kind: Service
metadata:
  name: lol-queue-server-v1
  labels:
    api: v1
    app: lol-queue-server-v1
    env: prod
spec:
  selector:
    api: v1
    app: lol-queue-server
    env: prod
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  type: LoadBalancer
