gcd:
  image: vantagesports/gcd-emulator:grpc
  ports:
    - "10015:8080"

lolstats:
  build: ../../
  dockerfile: ./cmd/goalsserver/Dockerfile
  volumes:
    - $GOPATH/src/github.com/VantageSports/lolstats:/go/src/github.com/VantageSports/lolstats
    - $GOPATH/src/github.com/VantageSports/lolstats/testdata:/tmp/testdata
  ports:
    # grpc port
    - "50015:50000"
    # debug http port
    - "9015:80"
  links:
    - "gcd"
  working_dir: /go/src/github.com/VantageSports/lolstats
  environment:
    - ADDR_USERS_V2=${DOCKER_GUEST}:50000
    - GOOG_CREDS_JSON=gcp-vs-dev.json
    - GOOG_PROJECT_ID=vs-dev
    - SIGN_KEY_INTERNAL=string:_fake_internal_key_
    - LOL_USERS_SERVER_ADDR=${DOCKER_GUEST}:50001
    - BIG_QUERY_TABLE_BASIC=vsd_lol.lolstats_basic
    - BIG_QUERY_TABLE_ADVANCED=vsd_lol.lolstats_advanced

  command: reflex -r '\.go$$' -s -- /bin/bash -c 'go install ./cmd/goalsserver && /go/bin/goalsserver'
