apiVersion: v1
kind: Service
metadata:
  name: lol-goals-server-v1
  labels:
    api: v1
    app: lol-goals-server
    env: prod
spec:
  selector:
    api: v1
    app: lol-goals-server
    env: prod
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
    nodePort: 32015
  type: LoadBalancer
