apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lol-users-server-v1
spec:
  replicas: 2
  minReadySeconds: 30
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: lol-users-server
        env: prod
        api: v1
    spec:
      containers:
      - env:
        - name: ADDR_USERS_V2
          value: users-server-v2.default.svc.cluster.local:443
        - name: ADDR_RIOT_PROXY
          value: lol-riotproxy-server-v1.default.svc.cluster.local:443
        - name: ADDR_TASKS_EMAIL
          value: tasks-email-server-v1.default.svc.cluster.local:443
        - name: GOOG_CREDS_JSON
          value: /etc/creds/gcp-vs-main
        - name: GOOG_PROJECT_ID
          value: vs-main
        - name: INSECURE_GRPC
          value: "true"
        - name: PORT
          value: :443
        - name: SIGN_KEY_INTERNAL
          value: file_trim:/etc/creds/internal-sign-key
        - name: PUBSUB_OUTPUT_TOPIC
          value: lol_summoner_crawl
        - name: LOL_ACTIVE_GROUP_ID
          value: "5744651969495040"
        - name: TLS_CERT
          value: /etc/ssl-certs/crt-pem
        - name: TLS_KEY
          value: /etc/ssl-certs/key-pem
        image: gcr.io/vs-containers/lol-users-server:change_me
        imagePullPolicy: Always
        name: lol-users-server-v1
        ports:
        - containerPort: 443
          protocol: TCP
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: 40m
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /etc/creds
          name: creds-prod
          readOnly: true
        - mountPath: /etc/ssl-certs
          name: ssl-certs
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: creds-prod
        secret:
          secretName: creds-prod
      - name: ssl-certs
        secret:
          secretName: sslcerts-vscom
