apiVersion: v1
kind: Service
metadata:
  name: lol-users-server-v1
spec:
  selector:
    api: v1
    app: lol-users-server
    env: staging
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
    nodePort: 32002
  type: LoadBalancer
