apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lol-summoner-crawler-runner-v1
spec:
  replicas: 1
  minReadySeconds: 30
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        api: v1
        app: lol-summoner-crawler-runner
        env: staging
    spec:
      containers:
      - env:
        - name: GOOG_PROJECT_ID
          value: vs-staging1
        - name: GOOG_CREDS_JSON
          value: /etc/creds/gcp-staging1
        - name: RIOT_API_KEY
          value: file_trim:/etc/creds/riot-api-key
        - name: INPUT_QUEUE_ID
          value: lol_summoner_crawl
        - name: MATCH_DOWNLOAD_QUEUE_ID
          value: lol_match_download
        - name: RECENT_GAMES_STORE_LOCATION
          value: gs://vss-esports/lol/crawl/matches
        - name: REQ_PER_10SEC
          value: "50"
        image: gcr.io/vs-containers/lol-summoner-crawler
        imagePullPolicy: Always
        name: lol-summoner-crawler-runner-v1
        resources:
          requests:
            cpu: 50m
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /etc/creds
          name: creds-staging
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: creds-staging
        secret:
          secretName: creds-staging
